Repository rackerlabs/design-system, pull requests merged in 2018-05, with the labels that each got.

#527 Tabs pattern updates to new IA
  _component_design/tabset.md
  assets/images/components/content-areas/tabs/tabs-content-area.svg
  assets/images/components/content-areas/tabs/tabs-hover-state.svg
  assets/images/components/content-areas/tabs/tabs-lorem-ipsum.svg
  assets/images/components/content-areas/tabs/tabs-menu.svg
  assets/images/components/content-areas/tabs/tabs-pressed-state.svg
  assets/images/components/content-areas/tabs/tabs-spacing.png
  assets/images/components/content-areas/tabs/tabs-state-hover.png
  assets/images/components/content-areas/tabs/tabs-state-pressed.png
  assets/images/components/content-areas/tabs/tabs-state-zero.png
  assets/images/components/content-areas/tabs/tabs-style.png
  assets/images/components/content-areas/tabs/tabs-zero-state.svg
  assets/images/components/content-areas/tabs/tabs_composition.png
Labels: WIP, status-needs-final-signoff, status-needs-review, type-documentation

#526 Popovers pattern updated to new IA
  _component_design/popovers.md
  assets/images/components/content-areas/popovers/popover-default-layout.svg
  assets/images/components/content-areas/popovers/popover-hero-image.svg
  assets/images/components/content-areas/popovers/popover-large-hidden-content.svg
  assets/images/components/content-areas/popovers/popover-loading.svg
  assets/images/components/content-areas/popovers/popover-pointer-size-placement.svg
  assets/images/components/content-areas/popovers/popover-small-create-edit-popover.svg
  assets/images/components/content-areas/popovers/popover-small-create-edit.svg
  assets/images/components/content-areas/popovers/popover-spacing.svg
  assets/images/components/content-areas/popovers/popover-specs.svg
  assets/images/components/content-areas/popovers/popovers-composition.png
  assets/images/components/content-areas/popovers/popovers-hidden-content-popover.png
  assets/images/components/content-areas/popovers/popovers-loading-state.png
  assets/images/components/content-areas/popovers/popovers-size-and-spacing.png
  assets/images/components/content-areas/popovers/popovers-small-create-edit-popover.png
  assets/images/components/content-areas/popovers/popovers-spacing.png
  assets/images/components/content-areas/popovers/popovers-style.png
Labels: WIP, status-needs-final-signoff, status-needs-review, type-documentation

#511 Modals pattern update - review required
  _component_design/modal.md
  assets/images/components/content-areas/modal/modal-composition.svg
  assets/images/components/content-areas/modal/modal-hero-image.svg
  assets/images/components/content-areas/modal/modal-loading.svg
  assets/images/components/content-areas/modal/modal-spacing.svg
  assets/images/components/content-areas/modal/modal-specifications.svg
  assets/images/components/content-areas/modal/modal-use-case-confirmations.svg
  assets/images/components/content-areas/modal/modals-acknowledgement-modal.png
  assets/images/components/content-areas/modal/modals-composition.png
  assets/images/components/content-areas/modal/modals-confirmation-modals.png
  assets/images/components/content-areas/modal/modals-educational-modal-composition.png
  assets/images/components/content-areas/modal/modals-educational-modal-grid.png
  assets/images/components/content-areas/modal/modals-educational-modal-spacing.png
  assets/images/components/content-areas/modal/modals-educational-modal-style.png
  assets/images/components/content-areas/modal/modals-educational-modal.png
  assets/images/components/content-areas/modal/modals-loading.png
  assets/images/components/content-areas/modal/modals-spacing.png
  assets/images/components/content-areas/modal/modals-style.png
Labels: WIP, prio-1, status-doing, type-documentation

#522 Surf 1036
  _component_design/progress-bar.md
  assets/images/components/processing/progress-bar/progress-behavior.png
  assets/images/components/processing/progress-bar/progress-composition.png
  assets/images/components/processing/progress-bar/progress-overview.png
  assets/images/components/processing/progress-bar/progress-spacing.png
  assets/images/components/processing/progress-bar/progress-specs.png
  assets/images/preview-images/progress-bar.svg
Labels: status-needs-response, status-needs-review, type-documentation, type-spec

#516 Add Shadows docs
  _docs/style/shadows.md
  assets/images/style/shadows/elevation-graphic.png
  assets/images/style/shadows/shadows-elevation.png
  assets/images/style/shadows/shadows-focus.png
  assets/images/style/shadows/shadows-layers.png
Labels: status-needs-review, type-documentation, type-enhancement

#525 Pills update to new IA
  _component_design/pills.md
  assets/images/components/content-areas/pills/pills-composition.png
  assets/images/components/content-areas/pills/pills-default.png
  assets/images/components/content-areas/pills/pills-hero.png
  assets/images/components/content-areas/pills/pills-spacing.png
  assets/images/components/content-areas/pills/pills-specs.png
  assets/images/components/content-areas/pills/pills-states-active.png
  assets/images/components/content-areas/pills/pills-states-hover.png
  assets/images/components/content-areas/pills/pills-states.png
  assets/images/components/content-areas/pills/pills-style.png
  assets/images/components/content-areas/pills/pills-too_long.png
Labels: WIP, status-doing, type-documentation
