Repository rackerlabs/design-system, pull requests merged in 2018-09, with the labels that each got.

#539 Drop-down buttons IA update
  _component_design/buttons-drop-down.md
  assets/css/_sass/website/_component-page.scss
  assets/images/components/inputs-and-controls/drop-down-buttons/buttons-dropdown-composition.png
  assets/images/components/inputs-and-controls/drop-down-buttons/buttons-dropdown-spacing.png
  assets/images/components/inputs-and-controls/drop-down-buttons/buttons-dropdown-style.png
  assets/images/preview-images/buttons-dropdown-thumbnail.svg
Labels: needs-technical-LGTM, type-documentation

#573 File tiles new IA
  _component_design/file-tile.md
  assets/images/components/content-areas/file-tiles/filetiles-composition-icon.png
  assets/images/components/content-areas/file-tiles/filetiles-composition.png
  assets/images/components/content-areas/file-tiles/filetiles-spacing.png
  assets/images/components/content-areas/file-tiles/filetiles-states-error.png
  assets/images/components/content-areas/file-tiles/filetiles-states-focus.png
  assets/images/components/content-areas/file-tiles/filetiles-states-hover.png
  assets/images/components/content-areas/file-tiles/filetiles-states-loading.png
  assets/images/components/content-areas/file-tiles/filetiles-states-readonly.png
  assets/images/components/content-areas/file-tiles/filetiles-style.png
  assets/images/preview-images/file-tiles_thumbnail.svg
Labels: needs-content-LGTM, type-documentation

#574 Buttons bar IA update
  _component_design/buttons-bar.md
  assets/images/components/inputs-and-controls/buttons-bar/buttonbar-composition.png
  assets/images/components/inputs-and-controls/buttons-bar/buttonbar-spacing.png
  assets/images/components/inputs-and-controls/buttons-bar/buttonbar-style.png
  assets/images/components/inputs-and-controls/buttons-bar/buttonbar-variations-primary.png
  assets/images/preview-images/buttons-bar.svg
Labels: needs-technical-LGTM, type-documentation

#578 Adding Richard Goodwin
  _data/helix-team.yml
  _docs/contact-us/index.md
Labels: status-html-review, status-needs-final-signoff
