Repository rackerlabs/design-system, pull requests merged in 2018-06, with the labels that each got.

#538 08 June 2018 weekly publication
  _component_design/tooltip.md
  assets/images/components/content-areas/tooltips/tooltips-behavior-click.png
  assets/images/components/content-areas/tooltips/tooltips-behavior-hover.png
  assets/images/components/content-areas/tooltips/tooltips-composition.png
  assets/images/components/content-areas/tooltips/tooltips-examples.png
  assets/images/components/content-areas/tooltips/tooltips-spacing.png
  assets/images/components/content-areas/tooltips/tooltips-state-loading.png
  assets/images/components/content-areas/tooltips/tooltips-style-pointer.png
  assets/images/components/content-areas/tooltips/tooltips-style.png
  assets/images/components/content-areas/tooltips/tooltips-variations-large.png
  assets/images/components/content-areas/tooltips/tooltips-variations-link.png
  assets/images/components/help/tooltips/tooltip-click.svg
  assets/images/components/help/tooltips/tooltip-composition.svg
  assets/images/components/help/tooltips/tooltip-hero.svg
  assets/images/components/help/tooltips/tooltip-hover.svg
  assets/images/components/help/tooltips/tooltip-large-tooltips.svg
  assets/images/components/help/tooltips/tooltip-loading.svg
  assets/images/components/help/tooltips/tooltip-pointer-placement.svg
  assets/images/components/help/tooltips/tooltip-spacing-1.svg
  assets/images/components/help/tooltips/tooltip-spacing-2.svg
  assets/images/components/help/tooltips/tooltip-text-conventions-1.svg
  assets/images/components/help/tooltips/tooltip-text-with-link.svg
  assets/images/components/help/tooltips/tooltip-triggers.svg
Labels: status-needs-final-signoff, type-website

#541 Vertical stepper updates to IA
  _component_design/vertical-stepper.md
  assets/images/components/content-areas/vert-stepper/vert-stepper-buttons.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-clickable.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-composition.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-counter.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-error-1.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-error-2.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-hero.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-loading.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-spacing.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-specs.png
  assets/images/components/content-areas/vert-stepper/vstepper-composition-buttonlogic.png
  assets/images/components/content-areas/vert-stepper/vstepper-composition.png
  assets/images/components/content-areas/vert-stepper/vstepper-generic.png
  assets/images/components/content-areas/vert-stepper/vstepper-spacing.png
  assets/images/components/content-areas/vert-stepper/vstepper-state-loading.png
  assets/images/components/content-areas/vert-stepper/vstepper-states-error.png
  assets/images/components/content-areas/vert-stepper/vstepper-style-clickablearea.png
  assets/images/components/content-areas/vert-stepper/vstepper-style-counter.png
Labels: type-documentation

#537 Simple buttons - ready for final signoff
  _component_design/buttons.md
  _component_design/simple-buttons.md
  assets/images/components/inputs-and-controls/buttons/buttons-hero.svg
  assets/images/components/inputs-and-controls/buttons/buttons-loading-1.svg
  assets/images/components/inputs-and-controls/buttons/buttons-loading-2.svg
  assets/images/components/inputs-and-controls/buttons/buttons-primary.svg
  assets/images/components/inputs-and-controls/buttons/buttons-secondary.svg
  assets/images/components/inputs-and-controls/buttons/buttons-sets-1.svg
  assets/images/components/inputs-and-controls/buttons/buttons-sets-2.svg
  assets/images/components/inputs-and-controls/buttons/buttons-sets-3.svg
  assets/images/components/inputs-and-controls/buttons/buttons-simple.svg
  assets/images/components/inputs-and-controls/buttons/buttons-specs.svg
  assets/images/components/inputs-and-controls/buttons/buttons-tertiary.svg
  assets/images/components/inputs-and-controls/buttons/download-buttons-overview.png
  assets/images/components/inputs-and-controls/buttons/download-buttons-specs.png
  assets/images/components/inputs-and-controls/buttons/drop-button-hero.svg
  assets/images/components/inputs-and-controls/buttons/drop-buttons-hero.svg
  assets/images/components/inputs-and-controls/buttons/drop-buttons-specs.svg
  assets/images/components/inputs-and-controls/buttons/split-drop-buttons-hero.svg
  assets/images/components/inputs-and-controls/buttons/split-drop-buttons-specs.png
  assets/images/components/inputs-and-controls/buttons/split-drop-buttons-specs.svg
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-composition.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-spacing.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-states-focus.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-states-loading.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-style.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-variations-buttonsets.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-variations-primary.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-variations-secondary.png
  assets/images/components/inputs-and-controls/simple-buttons/buttons-simple-variations-tertiary.png
Labels: status-needs-response, type-documentation
