Repository rackerlabs/design-system, pull requests merged in 2018-02, with the labels that each got.

#431 docs(layout): add dual panel layout
  _docs/layout/page-layouts.md
  assets/images/layout/page-layouts/dual-panel-sidenav.png
  assets/images/layout/page-layouts/dual-panel-topnav.png
  assets/images/layout/page-layouts/layout-content-full-side-nav.png
  assets/images/layout/page-layouts/layout-content-full-top-nav.png
  assets/images/layout/page-layouts/layout-dashboard-top-nav.png
  assets/images/layout/page-layouts/layout-dual-panel-sidenav.png
  assets/images/layout/page-layouts/layout-dual-panel-topnav.png
  assets/images/layout/page-layouts/layout-left-side-rail-side-nav.png
  assets/images/layout/page-layouts/layout-left-side-rail-top-nav.png
  assets/images/layout/page-layouts/layout-navigation-side.png
  assets/images/layout/page-layouts/layout-navigation-top.png
  assets/images/layout/page-layouts/layout-right-side-rail-side-nav.png
  assets/images/layout/page-layouts/layout-right-side-rail-top-nav.png
Labels: status-needs-review, type-documentation

#439 docs(lists): add list.md page and images
  _component_design/lists.md
  assets/images/components/content-areas/lists/ordered-list.png
  assets/images/components/content-areas/lists/unordered-list.png
  assets/images/preview-images/list.svg
Labels: status-needs-help, status-needs-review, type-documentation

#440 docs(assisted-search): update assisted search docs
  _component_design/assisted-search.md
  assets/images/components/search-and-filters/search-assisted/assisted-search-active.png
  assets/images/components/search-and-filters/search-assisted/assisted-search-container-elements.png
  assets/images/components/search-and-filters/search-assisted/assisted-search-container.png
  assets/images/components/search-and-filters/search-assisted/assisted-search-layout-specifications.png
  assets/images/components/search-and-filters/search-assisted/assisted-search-loading-state.png
  assets/images/components/search-and-filters/search-assisted/assisted-search-post-entry.png
  assets/images/components/search-and-filters/search-assisted/assisted-search-pre-entry.png
  assets/images/components/search-and-filters/search-assisted/search-assisted-hero.png
Labels: status-needs-review, type-documentation, type-spec

#444 docs(download-btn): adds download btns to buttons.md
  _component_design/assisted-search.md
  _component_design/buttons.md
  assets/images/components/inputs-and-controls/buttons/download-buttons-overview.png
  assets/images/components/inputs-and-controls/buttons/download-buttons-specs.png
Labels: status-needs-information, status-needs-review, type-documentation

#443 docs(pills): add documentation for pills
  _component_design/pills.md
  assets/images/components/content-areas/pills/pills-default.png
  assets/images/components/content-areas/pills/pills-hero.png
  assets/images/components/content-areas/pills/pills-specs.png
  assets/images/components/content-areas/pills/pills-states.png
  assets/images/preview-images/pills.svg
Labels: status-needs-help, status-needs-review, type-documentation

#415 Search Capabilities
  _docs/layout/architecture.md
  _docs/layout/demo-options.md
  _docs/layout/footer.md
  _docs/layout/global-layer.md
  _docs/layout/grid.md
  _docs/layout/page-layouts.md
  _docs/resources/glossary.md
  _docs/style/colors.md
  _docs/style/date-time.md
  _docs/style/iconography.md
  _docs/style/typography.md
  _docs/style/voice-tone.md
  assets/css/_sass/website/_search.scss
  assets/css/website.scss
  assets/images/helix_icon.svg
  assets/js/search.js
  feed.json
  search.html
  templates/_includes/footer.html
  templates/_includes/nav.html
  templates/_includes/search-box.html
  templates/search.html
Labels: status-needs-final-signoff, status-needs-review, type-enhancement, type-website

#446 quietly fixes the search page link on staging...
  templates/_includes/search-box.html
Labels: status-needs-final-signoff, type-bug

#447 Fix search on staging
  templates/_includes/search-box.html
Labels: status-needs-final-signoff, type-bug

#448 docs(icons): update iconography documentation
  _data/icons.csv
  _docs/style/iconography.md
  assets/images/style/icons/icon-alert-colors.png
  assets/images/style/icons/icon-color.png
  assets/images/style/icons/icon-grid.png
  assets/images/style/icons/icon-shape.png
  assets/images/style/icons/icon-silhouette.png
  assets/images/style/icons/icon-sizing.png
  assets/images/style/icons/icon-weight.png
Labels: status-needs-help, status-needs-review, type-documentation

#434 docs(stepper): add in-progress vert-stepper docs
  _component_design/vertical-stepper.md
  assets/images/components/content-areas/vert-stepper/vert-stepper-buttons.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-clickable.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-composition.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-counter.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-error-1.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-error-2.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-hero.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-loading.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-spacing.png
  assets/images/components/content-areas/vert-stepper/vert-stepper-specs.png
Labels: status-needs-review, type-documentation
