Repository rackerlabs/design-system, pull requests merged in 2018-04, with the labels that each got.

#495 update(logos): adds updated logo from legal and adds color variations
  _docs/style/iconography.md
Labels: status-needs-final-signoff, type-enhancement

#496 6 April 2018 weekly publication
  _docs/style/iconography.md
Labels: status-needs-final-signoff

#497 Sketch library docs
  _docs/getting-started/design.md
  _docs/resources/design-resources.md
  _docs/resources/index.md
  _docs/resources/sketch-library.md
  assets/css/_sass/website/_shame.scss
  assets/images/codepen.svg
  assets/images/install-sketch-library/Add-library-1.png
  assets/images/install-sketch-library/Add-library-2.png
  assets/images/install-sketch-library/Add-library-3.png
  assets/images/install-sketch-library/Add-library-4.png
  assets/images/install-sketch-library/add-to-my-drive.png
  assets/images/install-sketch-library/backup-my-laptop.png
  assets/images/install-sketch-library/download-from-github.png
  assets/images/install-sketch-library/shared-drive.png
  assets/images/install-sketch-library/sync-helix-folder.png
  assets/images/lo-fi.svg
  assets/images/mark-github.svg
  assets/images/palette-contrast.svg
  assets/images/sketch-library.svg
  index.md
  templates/_includes/nav.html
Labels: status-needs-final-signoff, type-enhancement

#504 fix(stepper): update image to reference correct HEX
  assets/images/components/content-areas/vert-stepper/vert-stepper-counter.png
Labels: status-needs-final-signoff, type-bug

#505 docs(alerts): adjust specs to match HelixUI implementation
  _component_design/alert-bar.md
  assets/images/components/content-areas/alerts/alert-bar-composition.png
  assets/images/components/content-areas/alerts/alert-bar-composition.svg
  assets/images/components/content-areas/alerts/alert-bar-multiline-alerts.png
  assets/images/components/content-areas/alerts/alert-bar-multiline-alerts.svg
  assets/images/components/content-areas/alerts/alert-bar-specs.png
  assets/images/components/content-areas/alerts/alert-bar-specs.svg
  assets/images/components/content-areas/alerts/alert-bar-status-types.png
  assets/images/components/content-areas/alerts/alert-bar-status-types.svg
  assets/images/overview/accessibility/accessibility-alerts.png
Labels: status-needs-review, type-bug, type-documentation

#506 docs(spacing): adjust large container spacing, add XL / 2XL spacing
  _docs/style/spacing.md
  assets/images/style/spacing/spacing-system-container-spacing-variants.png
Labels: status-needs-review, type-enhancement, type-spec

#514 20 April 2018 weekly publication
  _component_design/alert-bar.md
  _component_design/key-value-pairs.md
  _docs/style/spacing.md
  assets/images/components/content-areas/alerts/alert-bar-composition.png
  assets/images/components/content-areas/alerts/alert-bar-composition.svg
  assets/images/components/content-areas/alerts/alert-bar-multiline-alerts.png
  assets/images/components/content-areas/alerts/alert-bar-multiline-alerts.svg
  assets/images/components/content-areas/alerts/alert-bar-specs.png
  assets/images/components/content-areas/alerts/alert-bar-specs.svg
  assets/images/components/content-areas/alerts/alert-bar-status-types.png
  assets/images/components/content-areas/alerts/alert-bar-status-types.svg
  assets/images/components/content-areas/key-pairs/key-value-vertical-composition.png
  assets/images/components/content-areas/key-pairs/key-value-vertical-loading.png
  assets/images/components/content-areas/key-pairs/keyvalue_composition.png
  assets/images/overview/accessibility/accessibility-alerts.png
  assets/images/style/spacing/spacing-system-container-spacing-variants.png
  templates/_includes/toc.html
Labels: status-needs-final-signoff, type-website
