Repository rackerlabs/design-system, pull requests merged in 2018-07, with the labels that each got.

#536 Text conventions
  _docs/style/date-time.md
  _docs/style/text-conventions/alert-messages.md
  _docs/style/text-conventions/capitalization.md
  _docs/style/text-conventions/date-time.md
  _docs/style/text-conventions/punctuation.md
  _docs/style/text-conventions/text-conventions.md
  _docs/style/text-conventions/voice-and-tone.md
  _docs/style/text-conventions/writing-guidelines.md
  assets/css/_sass/website/_do-dont-table.scss
  assets/css/_sass/website/_shame.scss
  assets/css/website.scss
  templates/_includes/nav.html
Labels: WIP, needs-content-LGTM, needs-technical-LGTM

#546 Fix for URL for text conventions
  _docs/style/text-conventions/text-conventions.md
Labels: needs-technical-LGTM, status-needs-final-signoff, type-bug

#552 13 July 2018 weekly publication
  _docs/style/date-time.md
  _docs/style/text-conventions/alert-messages.md
  _docs/style/text-conventions/capitalization.md
  _docs/style/text-conventions/date-time.md
  _docs/style/text-conventions/punctuation.md
  _docs/style/text-conventions/text-conventions.md
  _docs/style/text-conventions/voice-and-tone.md
  _docs/style/text-conventions/writing-guidelines.md
  assets/css/_sass/website/_do-dont-table.scss
  assets/css/_sass/website/_shame.scss
  assets/css/website.scss
  templates/_includes/nav.html
Labels: status-needs-final-signoff

#547 Surf 1149 when to engage helix
  ISSUE_TEMPLATE.md
  _data/contact-helix-illos.yml
  _data/helix-team.yml
  _docs/contact-us/index.md
  _docs/resources/index.md
  _docs/resources/sketch-library.md
  assets/css/_sass/website/_contact-us.scss
  assets/css/_sass/website/_shame.scss
  assets/css/website.scss
  assets/images/contact-us/andrew-raiford.png
  assets/images/contact-us/awareness-include-helix-member.png
  assets/images/contact-us/awareness-ready-to-design.png
  assets/images/contact-us/bart-renner.png
  assets/images/contact-us/cathy-siller.png
  assets/images/contact-us/christopher-moyer.png
  assets/images/contact-us/feedback-and-review-helix-looks-ugly.png
  assets/images/contact-us/feedback-and-review-tweaking-helix.png
  assets/images/contact-us/feedback-and-review-using-helix-correctly.png
  assets/images/contact-us/identified-a-gap-content-does-not-fit.png
  assets/images/contact-us/identified-a-gap-creating-something-new.png
  assets/images/contact-us/identified-a-gap-found-a-bug.png
  assets/images/contact-us/laura-santamaria.png
  assets/images/contact-us/mia-chung.png
  assets/images/contact-us/nate-archer.png
  assets/images/contact-us/roman-gonzalez.png
  assets/images/contact-us/ryan-johnson.png
  assets/images/contact-us/satish-chandrasekaran.png
  assets/images/contact-us/shaleen-agarwal.png
  templates/_includes/nav.html
Labels: status-needs-response, type-documentation

#549 Radio buttons - new IA
  _component_design/radio-buttons.md
  assets/images/components/inputs-and-controls/radio-buttons/radio-composition.png
  assets/images/components/inputs-and-controls/radio-buttons/radio-composition.svg
  assets/images/components/inputs-and-controls/radio-buttons/radio-error.png
  assets/images/components/inputs-and-controls/radio-buttons/radio-error.svg
  assets/images/components/inputs-and-controls/radio-buttons/radio-hero.png
  assets/images/components/inputs-and-controls/radio-buttons/radio-hero.svg
  assets/images/components/inputs-and-controls/radio-buttons/radio-spacing.png
  assets/images/components/inputs-and-controls/radio-buttons/radio-spacing.svg
  assets/images/components/inputs-and-controls/radio-buttons/radio-states.png
  assets/images/components/inputs-and-controls/radio-buttons/radio-states.svg
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-composition.png
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-spacing.png
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-states-disabled.png
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-states-enabled.png
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-states-error-group.png
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-states-error-required.png
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-states-error.png
  assets/images/components/inputs-and-controls/radio-buttons/radiobuttons-style.png
Labels: type-documentation
