Repository rackerlabs/design-system, pull requests merged in 2018-10, with the labels that each got.

#580 Changed 'Simple Buttons' to 'Buttons' throughout
  _component_design/button-bars.md
  _component_design/buttons-drop-down.md
  _component_design/buttons.md
  _component_design/selector-strip.md
  assets/images/components/inputs-and-controls/button-bars/buttonbar-composition.png
  assets/images/components/inputs-and-controls/button-bars/buttonbar-spacing.png
  assets/images/components/inputs-and-controls/button-bars/buttonbar-style.png
  assets/images/components/inputs-and-controls/button-bars/buttonbar-variations-primary.png
  assets/images/components/inputs-and-controls/buttons/buttons-composition.png
  assets/images/components/inputs-and-controls/buttons/buttons-hero.png
  assets/images/components/inputs-and-controls/buttons/buttons-spacing.png
  assets/images/components/inputs-and-controls/buttons/buttons-states-focus.png
  assets/images/components/inputs-and-controls/buttons/buttons-states-loading.png
  assets/images/components/inputs-and-controls/buttons/buttons-style.png
  assets/images/components/inputs-and-controls/buttons/buttons-variations-buttonsets.png
  assets/images/components/inputs-and-controls/buttons/buttons-variations-primary.png
  assets/images/components/inputs-and-controls/buttons/buttons-variations-secondary.png
  assets/images/components/inputs-and-controls/buttons/buttons-variations-tertiary.png
Labels: type-documentation

#579 Icon buttons - new IA
  _component_design/button-iconography.md
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-icononly-composition.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-icononly-examples-common.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-icononly-examples-modtert-cog.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-icononly-examples-secondary-filter.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-icononly-spacing.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-icononly-states-modtertiary.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-icononly-style.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-txtwicon-composition.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-txtwicon-spacing.png
  assets/images/components/inputs-and-controls/button-iconography/buttoniconography-txtwicon-style.png
  assets/images/preview-images/button-icon_thumbnail.svg
Labels: type-documentation

#588 chore(version bump): bumping the toolkit version; updating statuses
  _component_design/button-bars.md
  _component_design/button-iconography.md
  _component_design/buttons-drop-down.md
  node_modules/.yarn-integrity
  node_modules/helix-ui/dist/scripts/helix-ui.browser.js
  node_modules/helix-ui/dist/scripts/helix-ui.browser.min.js
  node_modules/helix-ui/dist/scripts/helix-ui.es.js
  node_modules/helix-ui/dist/scripts/helix-ui.js
  node_modules/helix-ui/dist/styles/helix-ui.css
  node_modules/helix-ui/dist/styles/helix-ui.min.css
  package.json
  yarn.lock
Labels: needs-technical-LGTM, status-needs-final-signoff, type-website

#571 fix(anchor): fixing anchor by changing headings
  _docs/style/spacing.md
Labels: status-needs-final-signoff, type-bug

#587 Text fields new IA
  _component_design/input-selectors.md
  _component_design/progress-bar.md
  _component_design/search.md
  _component_design/text-fields.md
  _component_design/text-input.md
  assets/images/components/inputs-and-controls/text-fields/text-fields-hero-image.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-area-basic-layout.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-area-states-overview.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-basic-layout.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-character-or-word-counter.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-disabled.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-focused.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-helper-text.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-invalid.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-password-redaction.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-placeholder-text.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-prefixes-and-suffixes.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-required.svg
  assets/images/components/inputs-and-controls/text-fields/text-fields-text-input-states-overview.svg
  assets/images/components/inputs-and-controls/text-input/textinput-composition.png
  assets/images/components/inputs-and-controls/text-input/textinput-disabled.png
  assets/images/components/inputs-and-controls/text-input/textinput-spacing.png
  assets/images/components/inputs-and-controls/text-input/textinput-states-enabled.png
  assets/images/components/inputs-and-controls/text-input/textinput-states-error.png
  assets/images/components/inputs-and-controls/text-input/textinput-style.png
  assets/images/components/inputs-and-controls/text-input/textinput-variations-prefixes.png
  assets/images/components/inputs-and-controls/text-input/textinput-variations-redaction.png
  assets/images/components/inputs-and-controls/text-input/textinput-variations-textareas.png
Labels: type-documentation

#589 Team Update
  _data/helix-team.yml
Labels: status-needs-final-signoff, type-documentation

#590 Rename input selector
  _component_design/checkboxes.md
  _component_design/drop-down-selector.md
  assets/images/components/inputs-and-controls/drop-down-selector/drop-down-selector-composition.png
  assets/images/components/inputs-and-controls/drop-down-selector/drop-down-selector-spacing.png
  assets/images/components/inputs-and-controls/drop-down-selector/drop-down-selector-states-toomany.png
  assets/images/components/inputs-and-controls/drop-down-selector/drop-down-selector-states.png
  assets/images/components/inputs-and-controls/drop-down-selector/drop-down-selector-style.png
Labels: status-needs-review
